Add media folder rsync to sync_prod

diff --git a/scripts/sync_prod b/scripts/sync_prod
--- a/scripts/sync_prod
+++ b/scripts/sync_prod
@@ -61,6 +61,10 @@ if [[ storageDir == "null" ]]
   then
     storageDir=${PWD}
 fi
+
+# create a storage dir just in case it doesn't exist
+mkdir -p "${storageDir}"
+
 # This loop avoids issues with spaces in values, although they probably
 # shouldn't be there in the first place
 while IFS= read -r line
@@ -77,7 +81,7 @@ do
       echo "Missing host or database key in ${i}." 1>&2
       exit 1
   fi
-  # On a dry run, just say what it ough tto connect to
+  # On a dry run, just say what it ought to connect to
   # and also what files would be deleted based on the configured
   # storageDir
   if  [[ $dryrun ]]
@@ -89,8 +93,9 @@ do
   else
     # Otherwise, connect to host, dump to tmp file
     echo "Connecting to ${host}..."
-    ssh -o ConnectTimeout=5 "${host}" mysqldump --opt "${db}" > "${tmp_file}"
-    retVal=$?
+    # continue on an error but set an error code so we know there was a problem
+    ssh -o ConnectTimeout=5 \
+    "${host}" mysqldump --opt "${db}" > "${tmp_file}" || EXIT_CODE=$? && true
     if [[ $retVal -ne 0 ]]
       then
         echo "Could not dump database $db for $host" 1>&2
@@ -108,5 +113,35 @@ do
   fi
 done
 
-# if SSH error was logged, bubble it up via exit code.
+# dump files
+for i in "${applications[@]}"
+do
+  mediaDir=$(echo ${i} | jq -r ".mediaDir")
+  host=$(echo ${i} | jq -r ".host")
+  # no mediaDir specified or empty string
+  if [[ $mediaDir == "null" ]] || [[ -z $mediaDir  ]]
+    then
+      continue
+  fi
+
+  if [[ $dryrun ]]
+    then
+      echo "Would rsync ${mediaDir} as ${storageDir}/media/${host}."
+  else
+    echo "Rsyncing media for ${host}"
+    # make sure the folder exists
+    mkdir -p "${storageDir}/media/${host}"
+    # rsync over the files and maintain a link
+    # continue on an error but set an error code so we know there was a problem
+    rsync -r "${host}:${mediaDir}" "${storageDir}/media/${host}/" || EXIT_CODE=$? && true
+    if [[ $retVal -ne 0 ]]
+      then
+        echo "Could not rsync media for $host" 1>&2
+        error=true
+        break
+    fi
+  fi
+done
+
+# if SSH or rsync error was logged, bubble it up via exit code.
 if [[ $error ]]; then exit 1; fi
